services:
  - type: web
    name: rag-pipeline
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -w 4 -k uvicorn.workers.UvicornWorker app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9